
INSERT INTO User (ID,NAME,ROLE,USERNAME,PASSWORD) VALUES (1,'Aadeesh','USER','aadeeshjain','abcd@234');
INSERT INTO User (ID,NAME,ROLE,USERNAME,PASSWORD) VALUES (2,'Andrew','USER','andrewjate','andrew@9');
INSERT INTO User (ID,NAME,ROLE,USERNAME,PASSWORD) VALUES (3,'John','MANAGER','john619','john@3113');
INSERT INTO User (ID,NAME,ROLE,USERNAME,PASSWORD) VALUES (4,'Peter','MANAGER','peterp','pet_er@9');

